### ISSUE TITLE
Give us a version for 2018

### ISSUE THREAD

**Issue by smabukhari** [Radeon-ProRender/Max#14]
Hi,
Can you please provide a version for 3ds max 2018. If you can provide source along with instructions to compile on vs 2017 then it will be much appreciated.

I have Ryzen 1700 with RX580 8GB and would love to check it out on my pc.

**Comment by Renderking** [comment]
I also would be intersted in this.
We could much more play around with the renderer and contribute to the plugin.

**Comment by bsavery** [comment]
Done.

**Comment by bsavery** [comment]
Support for 2018 is added Source may be added here in the future.  Stay tuned.
